# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.9"
    - name: Install poetry
        # https://github.com/abatilo/actions-poetry
      uses: abatilo/actions-poetry@v3.0.0
      with:
        poetry-version: 1.8.3
    - name: Install dependencies
      run: poetry install --no-root
    - name: Lint with isort
      run: |
        poetry run isort .
      continue-on-error: true
    - name: Lint with black
      run: |
        poetry run black --check .
      continue-on-error: true
    - name: Lint with pycln
      run: |
        poetry run pycln --all .
      continue-on-error: true
    - name: Lint with mypy
      run: |
        poetry run mypy .
      continue-on-error: true
    - name: Test with pytest
      run: |
        poetry run pytest